"""Update models: add user_id to Doctor, role to User, additional fields to Appointment, new Feedback model

Revision ID: d5186ebc73bf
Revises: 323ccabc899d
Create Date: 2025-10-15 08:27:50.120579

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd5186ebc73bf'
down_revision = '323ccabc899d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feedbacks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('visit_type', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('reschedule_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('doctor_response', sa.String(length=20), nullable=True))

    with op.batch_alter_table('doctors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('availability', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('fees', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('rating', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('location', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('contact_info', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('verified', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('visit_types', sa.Text(), nullable=True))
        batch_op.create_unique_constraint(None, ['user_id'])
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.Enum('PATIENT', 'DOCTOR', 'ADMIN', name='userrole'), nullable=True))
        batch_op.add_column(sa.Column('address', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('city', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('dob', sa.Date(), nullable=True))
        batch_op.drop_column('is_admin')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
        batch_op.drop_column('dob')
        batch_op.drop_column('city')
        batch_op.drop_column('address')
        batch_op.drop_column('role')

    with op.batch_alter_table('doctors', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('visit_types')
        batch_op.drop_column('verified')
        batch_op.drop_column('contact_info')
        batch_op.drop_column('location')
        batch_op.drop_column('rating')
        batch_op.drop_column('fees')
        batch_op.drop_column('availability')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.drop_column('doctor_response')
        batch_op.drop_column('reschedule_count')
        batch_op.drop_column('notes')
        batch_op.drop_column('visit_type')

    op.drop_table('feedbacks')
    # ### end Alembic commands ###
